config/routes.rb
Rails.application.routes.draw do
  resources :password_managers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'static_pages#index'

  get 'sobre', to: 'static_pages#sobre'
  get 'contato', to: 'static_pages#contato'

  #resources :static_pages, only: %i[sobre contato]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/password_manager.rb
class PasswordManager < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/password_managers_controller.rb
class PasswordManagersController < ApplicationController
  before_action :set_password_manager, only: %i[ show edit update destroy ]

  # GET /password_managers or /password_managers.json
  def index
    @password_managers = PasswordManager.all
  end

  # GET /password_managers/1 or /password_managers/1.json
  def show
  end

  # GET /password_managers/new
  def new
    @password_manager = PasswordManager.new
  end

  # GET /password_managers/1/edit
  def edit
  end

  # POST /password_managers or /password_managers.json
  def create
    @password_manager = PasswordManager.new(password_manager_params)

    respond_to do |format|
      if @password_manager.save
        format.html { redirect_to password_manager_url(@password_manager), notice: "Password manager was successfully created." }
        format.json { render :show, status: :created, location: @password_manager }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @password_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /password_managers/1 or /password_managers/1.json
  def update
    respond_to do |format|
      if @password_manager.update(password_manager_params)
        format.html { redirect_to password_manager_url(@password_manager), notice: "Password manager was successfully updated." }
        format.json { render :show, status: :ok, location: @password_manager }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @password_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /password_managers/1 or /password_managers/1.json
  def destroy
    @password_manager.destroy

    respond_to do |format|
      format.html { redirect_to password_managers_url, notice: "Password manager was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_password_manager
      @password_manager = PasswordManager.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def password_manager_params
      params.require(:password_manager).permit(:name, :password)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def index; end

    def sobre

    end

    def contato
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_managers_helper.rb
module PasswordManagersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <%= link_to 'Contact List. Todos os direitos reservados.', root_path %>
  </small>

  <nav>
    <ul>
      <li>
        <%= link_to 'Sobre', sobre_path %>
      </li>
      <li>
        <%= link_to 'Contato', contato_path %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">

  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#expanded-menu" aria-expanded=" false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Contact List', root_url, class: 'navbar-brand' %>
    </div>

  <!-- Conteudo exibido em telas maiores e que serao escondidos em telas menores -->
  <div class="collapse navbar-collapse" id="expanded-menu">
    <ul class="nav navbar-nav">
      <% if true %>
        <li class="active">
          <%= link_to 'Nova Conta', '#' %>
        </li>
      <% end %>
    </ul>

    <ul class="nav navbar-nav navbar-right">

        <li>
          <%= link_to 'Entrar', '#' %>
      </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Bem vindo,  <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to 'Minha Pagina', '#' %>
            </li>
            <li>
              <%= link_to 'Editar', '#' %>
            </li>
            <li class="divider" role="separator"></li>
            <li>
              <%= link_to 'Sair', '#' %>
            </li>
          </ul>
        </li>

    </ul>

  </div>

  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <title>MemoryKey</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    
    <div class='container'>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/password_managers/_form.html.erb
<%= form_with(model: password_manager) do |form| %>
  <% if password_manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(password_manager.errors.count, "error") %> prohibited this password_manager from being saved:</h2>

      <ul>
        <% password_manager.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/password_managers/edit.html.erb
<h1>Editing Password Manager</h1>

<%= render 'form', password_manager: @password_manager %>

<%= link_to 'Show', @password_manager %> |
<%= link_to 'Back', password_managers_path %>

app/views/password_managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Password Managers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @password_managers.each do |password_manager| %>
      <tr>
        <td><%= password_manager.name %></td>
        <td><%= password_manager.password %></td>
        <td><%= link_to 'Show', password_manager %></td>
        <td><%= link_to 'Edit', edit_password_manager_path(password_manager) %></td>
        <td><%= link_to 'Destroy', password_manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Password Manager', new_password_manager_path %>

app/views/password_managers/new.html.erb
<h1>New Password Manager</h1>

<%= render 'form', password_manager: @password_manager %>

<%= link_to 'Back', password_managers_path %>

app/views/password_managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @password_manager.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @password_manager.password %>
</p>

<%= link_to 'Edit', edit_password_manager_path(@password_manager) %> |
<%= link_to 'Back', password_managers_path %>

app/views/static_pages/contato.html.erb
<h1>Contato</h1>

<p>
  Entre em contato com <a href='https://www.linkedin.com/in/lucas-andrade-bb2992183/'>Lucas de Andrade</a> para saber mais
</p>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <h1>Memory key</h1>
  <p>
    Gerencie suas senhas em qualquer lugar!
  </p>
  <p>
    <%= link_to 'Crie sua conta!', 'new_user_path', class: 'btn btn-primary btn-lg'%>
  </p>
</div>

app/views/static_pages/sobre.html.erb
<h1>Sobre</h1>

<p>
  Criado com o intuito de aprender na prática os conhecimentos adquiridos em Ruby on Rails,
  fazendo um crud básico para armazenar senhas.
</p>